In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import plotly.express as px
df = pd.read_csv("dataset-3.csv")
df

    id_start   id_end  distance
0    1001400  1001402       9.7
1    1001402  1001404      20.2
2    1001404  1001406      16.0
3    1001406  1001408      21.7
4    1001408  1001410      11.1
5    1001410  1001412      15.6
6    1001412  1001414      18.2
7    1001414  1001416      13.2
8    1001416  1001418      13.6
9    1001418  1001420      12.9
10   1001420  1001422       9.6
11   1001422  1001424      11.4
12   1001424  1001426      18.6
13   1001426  1001428      15.8
14   1001428  1001430       8.6
15   1001430  1001432       9.0
16   1001432  1001434       7.9
17   1001434  1001436       4.0
18   1001436  1001438       9.0
19   1001436  1001437       5.0
20   1001438  1001437       4.0
21   1001438  1001440      10.0
22   1001440  1001442       3.9
23   1001442  1001488       4.5
24   1001488  1004356       4.0
25   1004356  1004354       2.0
26   1004354  1004355       2.0
27   1004355  1001444       0.7
28   1001444  1001446       6.6
29   1001446  1001448       9.6
30   1001448  1001450      15.7
31   1001450  1001452       9.9
32   1001452  1001454      11.3
33   1001454  1001456      13.6
34   1001456  1001458       8.9
35   1001458  1001460       5.1
36   1001460  1001461      12.8
37   1001460  1001462      17.9
38   1001461  1001462       5.1
39   1001462  1001464      26.7
40   1001464  1001466       8.5
41   1001466  1001468      10.7
42   1001468  1001470      10.6
43   1001470  1001472      16.0

In [3]:
import pandas as pd

def calculate_distance_matrix(df: pd.DataFrame) -> pd.DataFrame:
    unique_ids = sorted(set(df['id_start'].unique()) | set(df['id_end'].unique()))
    distance_matrix = pd.DataFrame(index=unique_ids, columns=unique_ids)

    for _, row in df.iterrows():
        distance_matrix.loc[row['id_start'], row['id_end']] = row['distance']

    distance_matrix = distance_matrix.fillna(0)
    return distance_matrix

In [4]:
def unroll_distance_matrix(df: pd.DataFrame) -> pd.DataFrame:
    unrolled_df = df.melt(id_vars=['id_start'], var_name='id_end', value_name='distance')
    return unrolled_df

In [5]:
def find_ids_within_ten_percentage_threshold(df: pd.DataFrame, reference_id: int) -> pd.DataFrame:
    reference_avg_distance = df[df['id_start'] == reference_id]['distance'].mean()
    threshold = 0.1 * reference_avg_distance
    ids_within_threshold = df.groupby('id_start')['distance'].mean().loc[lambda x: (x >= reference_avg_distance - threshold) & (x <= reference_avg_distance + threshold)].index
    result_df = df[df['id_start'].isin(ids_within_threshold)]
    return result_df

In [6]:
def calculate_toll_rate(df: pd.DataFrame) -> pd.DataFrame:
    # Assuming the unrolled DataFrame contains columns 'id_start', 'id_end', 'distance', and 'car'
    toll_rate_df = df.copy()
    toll_rate_df['toll_rate'] = toll_rate_df['car'] * toll_rate_df['distance']
    return toll_rate_df

In [7]:
def calculate_time_based_toll_rates(df: pd.DataFrame) -> pd.DataFrame:
    # Assuming the DataFrame contains a 'timestamp' column representing time
    df['hour'] = df['timestamp'].dt.hour

    # Define time intervals
    bins = [0, 6, 12, 18, 24]